/** AI / product-management keyword filter for Tech News category (fetch-time). */
const AI_PM_PATTERNS: RegExp[] = [
  /\bai\b/i,
  /\bartificial intelligence\b/i,
  /\bmachine learning\b/i,
  /\bdeep learning\b/i,
  /\bllm\b/i,
  /\blarge language model/i,
  /\bgenerative ai\b/i,
  /\bgen ai\b/i,
  /\bopenai\b/i,
  /\banthropic\b/i,
  /\bclaude\b/i,
  /\bchatgpt\b/i,
  /\bgemini\b/i,
  /\bcopilot\b/i,
  /\bagentic\b/i,
  /\bautomation\b/i,
  /\bproduct management\b/i,
  /\bproduct manager\b/i,
  /\bproduct-led\b/i,
  /\bproduct manager\b/i,
  /\bproduct strategy\b/i,
  /\bproduct discovery\b/i,
  /\broadmap\b/i,
  /\buser research\b/i,
  /\bux\b/i,
  /\bstartup\b/i,
  /\bsaas\b/i,
  /\bventure\b/i,
  /\bfunding\b/i,
  /\bplatform\b/i,
  /\brobotics\b/i,
  /\bchip\b/i,
  /\bnvidia\b/i,
  /\bmeta ai\b/i,
  /\bgoogle ai\b/i,
  /\bmicrosoft\b/i,
  /\bapple intelligence\b/i,
  /\bdata\b/i,
  /\bcloud\b/i,
  /\bsoftware\b/i,
  /\bapp\b/i,
  /\bsmartphone\b/i,
  /\bev\b/i,
  /\btech\b/i,
];

export function matchesAiPmContent(title: string, summary: string): boolean {
  const text = `${title} ${summary}`;
  return AI_PM_PATTERNS.some((p) => p.test(text));
}
